version: '3.8'

services:
  calc_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - LOG_LEVEL=info
      - JWT_SECRET=your-secret-key
      - DB_PATH=/app/data/calc.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
